server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/site1/ {
        proxy_pass http://site1:8001/;
        proxy_set_header Host $host;
    }

    location /api/site2/ {
        proxy_pass http://site2:8002/;
        proxy_set_header Host $host;
    }

    location /api/site3/ {
        proxy_pass http://site3:8003/;
        proxy_set_header Host $host;
    }

    location /api/site4/ {
        proxy_pass http://site4:8004/;
        proxy_set_header Host $host;
    }

    location /api/site5/ {
        proxy_pass http://site5:8005/;
        proxy_set_header Host $host;
    }

    location /api/tracker/ {
        proxy_pass http://tracker:8007/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}
