services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pricewatch

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pricewatch"]
      interval: 5s
      timeout: 5s
      retries: 5

  site1:
    build:
      context: ./simulators/ecomm-site-1
    container_name: site1
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres

  site2:
    build:
      context: ./simulators/ecomm-site-2
    container_name: site2
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - postgres

  site3:

    build:
      context: ./simulators/ecomm-site-3

    container_name: site3

    ports:
      - "8003:8003"

    env_file:
      - .env

    depends_on:
      - postgres

  site4:

    build:
      context: ./simulators/ecomm-site-4

    container_name: site4

    ports:
      - "8004:8004"

    env_file:
      - .env

    depends_on:
      - postgres

  site5:
    build:
      context: ./simulators/ecomm-site-5
    container_name: site5
    ports:
      - "8005:8005"
    env_file:
      - .env
    depends_on:
      - postgres

  scrapper:
    build:
      context: ./workers/scraper           
      dockerfile: Dockerfile

    container_name: scrapper
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy  
      seed:
        condition: service_completed_successfully

    command: ["sh", "-c", "sleep 5 && python main.py"]

  seed:

    build:
      context: .
      dockerfile: scripts/Dockerfile

    container_name: seed

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "
        python scripts/seed_products.py &&
        python scripts/seed_vendor.py
        "

  tracker:
      build:
        context: ./tracker_api/api
        dockerfile: Dockerfile

      container_name: tracker

      restart: unless-stopped

      ports:
        - "8007:8007"

      env_file:
       - .env

      depends_on:
          postgres:
            condition: service_healthy
          seed:
            condition: service_completed_successfully
      command: >
          sh -c "
          sleep 5 &&
          uvicorn main:app --host 0.0.0.0 --port 8007"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
